export { SerpApiClient, searchSerpApi } from "./client";
export {
  SERPAPI_BASE_URL,
  SUPPORTED_ENGINES,
  hotelsSearchParamsSchema,
  mapsSearchParamsSchema,
  normalizeHotels,
  normalizeMapsPlaces,
  searchParamsSchema,
  serpApiHotelsResponseSchema,
  serpApiMapsResponseSchema,
  serpApiSearchResponseSchema,
  type NormalizedHotel,
  type NormalizedHotelsResponse,
  type NormalizedMapsPlace,
  type NormalizedMapsResponse,
  type NormalizedSearchResponse,
  type NormalizedSearchResultItem,
  type SerpApiEngine,
  type SerpApiHotelsResponse,
  type SerpApiMapsResponse,
  type ValidatedHotelsSearchParams,
  type ValidatedMapsSearchParams,
  type ValidatedSearchParams,
} from "./types";
